const CSRF_KEY_NAME = 'solid-web-id';
const CSRF_TOKEN_NAME = 'SLD-NGL';
const CSRF_RANDOMIZER_SALT = [
  'MJPURLCHAF',
  'QWERTYUIOP',
  'ASDFGHJKLP',
  'ZXCVBNMEWQ',
  'KXVYBGTNED',
  'POIUYTREWQ',
  'LKJHGFDSAM',
  'MNBVCXZPOI',
  'POXNQWZTWR',
  'LJHGFDSAXZ',
  'YOIUYTREWQ',
  'VCWERTYUIO',
];

export {
  CSRF_KEY_NAME,
  CSRF_TOKEN_NAME,
  CSRF_RANDOMIZER_SALT
};